//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.Simulator.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimulatorCoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimulatorCoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.Simulator.Core.Resources.SimulatorCoreResources", typeof(SimulatorCoreResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Hub Name.
        /// </summary>
        internal static string EditSimulator_EventHubName {
            get {
                return ResourceManager.GetString("EditSimulator_EventHubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry the key you have specified is already in use..
        /// </summary>
        internal static string Err_DuplicateKey {
            get {
                return ResourceManager.GetString("Err_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Send Message.
        /// </summary>
        internal static string SendMessage_CouldNotSendMessage {
            get {
                return ResourceManager.GetString("SendMessage_CouldNotSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR - Please Check Output.
        /// </summary>
        internal static string SendMessage_Error {
            get {
                return ResourceManager.GetString("SendMessage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending Message.
        /// </summary>
        internal static string SendMessage_ErrorSendingMessage {
            get {
                return ResourceManager.GetString("SendMessage_ErrorSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Binary Payload.
        /// </summary>
        internal static string SendMessage_InvalidBinaryPayload {
            get {
                return ResourceManager.GetString("SendMessage_InvalidBinaryPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Published.
        /// </summary>
        internal static string SendMessage_MessagePublished {
            get {
                return ResourceManager.GetString("SendMessage_MessagePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent.
        /// </summary>
        internal static string SendMessage_MessageSent {
            get {
                return ResourceManager.GetString("SendMessage_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access key is required..
        /// </summary>
        internal static string Simulator_AccessKeyIsRequired {
            get {
                return ResourceManager.GetString("Simulator_AccessKeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        internal static string Simulator_Connected {
            get {
                return ResourceManager.GetString("Simulator_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Simulator_Disconnected {
            get {
                return ResourceManager.GetString("Simulator_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing will Disconnect this session.  Do you wish to continue?.
        /// </summary>
        internal static string Simulator_EditDisconnect {
            get {
                return ResourceManager.GetString("Simulator_EditDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting.
        /// </summary>
        internal static string Simulator_ErrorConnecting {
            get {
                return ResourceManager.GetString("Simulator_ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Simulator_PasswordIsRequired {
            get {
                return ResourceManager.GetString("Simulator_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter access key.
        /// </summary>
        internal static string Simulator_PromptAccessKey {
            get {
                return ResourceManager.GetString("Simulator_PromptAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string Simulator_PromptPassword {
            get {
                return ResourceManager.GetString("Simulator_PromptPassword", resourceCulture);
            }
        }
    }
}
